### ISSUE TITLE
Crashed when starting in 1.16.5 with mod version 0.2.4

### ISSUE THREAD

**Issue by XiaoHuiHui233** [plusls/plusls-carpet-addition#15]
key crash log:
```
[Server] Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method checkDiamondEquip(Lnet/minecraft/class_1282;FLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V in pca.mixins.json:rule.renewableNethe
rite.MixinItemEntity from mod pca failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap plusls-carpet-addition-1.16.5-refmap.json
[Server]        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1381) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
[Server]        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
[Server]        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
[Server]        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
[Server]        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.12.12.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.12.12.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.12.jar:?]
[Server]        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
[Server]        at net.minecraft.class_2246.<clinit>(class_2246.java:99) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_3523.<clinit>(class_3523.java:13) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_5471.<clinit>(class_5471.java:11) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_5458.method_30573(class_5458.java:44) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_5458.method_30566(class_5458.java:75) ~[server-intermediary.jar:?]
[Server]        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
[Server]        at net.minecraft.class_5458.<clinit>(class_5458.java:74) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_2378.<clinit>(class_2378.java:237) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_2966.method_12851(class_2966.java:42) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.Main.main(Main.java:87) ~[server-intermediary.jar:?]
[Server]        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
[Server]        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
[Server]        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
[Server]        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
[Server]        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
```

environment:
- fabric-loader 0.12.12
- fabric-api 0.43.1
- minecraft 1.16.5

mod list:
- appleskin-fabric-mc1.16.x-2.2.0.jar
- BBOutlineReloaded-2.4-1.16.3-fabric.jar
- carpet-extra-1.16.5-1.4.43.jar
- carpet-tis-addition-mc1.16.5-v1.28.1.jar
- clean-logs-1.0.1.jar
- FabricProxy-1.4.7.jar
- fabric-api-0.41.3+1.16.jar
- fabric-carpet-1.16.5-1.4.44+v210714.jar
- fz-bbl-1.16.x-1.1.4.jar
- lithium-fabric-mc1.16.5-0.6.6.jar
- phosphor-fabric-mc1.16.2-0.8.0.jar
- plusls-carpet-addition-1.16.5-0.2.4.jar 
- servux-fabric-1.16.4-0.1.6.jar 
- syncmatica-0.2.6.jar
- voicechat-fabric-1.16.5-1.9.9.jar
- worldedit-mod-7.2.5-dist.jar
- wthit-2.10.11-fabric.jar

Is this a bug in version update or is it incompatible with the latest fabric or just a mod conflict?

**Comment by XiaoHuiHui233** [comment]
Test in 0.2.3, everything is ok. So it's probably a bug in version 0.2.4.

**Comment by plusls** [comment]
fixed.

**Comment by plusls** [comment]
这告诉我们，合并分支要及时，过几天就会忘记自己写了什么内容
