### ISSUE TITLE
[Bug] 木桶吞物品崩服

### ISSUE THREAD

**Issue by little-boluo** [plusls/plusls-carpet-addition#28]
### Minecraft Version

1.17.1服务器

### Plusls Carpet Addition Version

1.17.1-0.2.5

### Carpet Version

1.17.1-1.4.57+v220119

### Fabric API Version

0.46.1

### Description

以任何方式在木桶中放入物品均会崩服
将木桶中的物品转移到物品栏中，物品将会在单击物品栏后消失
通过排查发现仅有此mod导致

### To Reproduce

在开启防止铁砧过于昂贵设定后
以任何方式在木桶中放入物品均会崩服
将木桶中的物品转移到物品栏中，物品将会在单击物品栏后消失

### Log

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2022-09-02 19:52
Description: Ticking block entity

java.lang.NullPointerException: Cannot invoke "carpet.settings.ParsedRule.getBoolValue()" because the return value of "carpet.settings.SettingsManager.getRule(String)" is null
	at com.plusls.carpet.network.PcaSyncProtocol.syncBlockEntityToClient(PcaSyncProtocol.java:327)
	at net.minecraft.class_3719.method_5431(class_3719.java:1024)
	at net.minecraft.class_2621.method_5434(class_2621.java:109)
	at net.minecraft.class_2614.handler$cda000$lithiumExtract(class_2614.java:4170)
	at net.minecraft.class_2614.method_11241(class_2614.java:196)
	at net.minecraft.class_2614.method_31691(class_2614.java:104)
	at net.minecraft.class_2614.method_11243(class_2614.java:120)
	at net.minecraft.class_2614.method_31692(class_2614.java:104)
	at net.minecraft.class_2818$class_5563.redirect$zbo000$checkProcessTEs(class_2818.java:1010)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:886)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:941)
	at net.minecraft.class_1937.method_18471(class_1937.java:474)
	at net.minecraft.class_3218.method_18765(class_3218.java:422)
	at net.minecraft.server.MinecraftServer.redirect$zim000$fixUpdateSuppressionCrashTick(MinecraftServer.java:4284)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:891)
	at net.minecraft.class_3176.method_3813(class_3176.java:335)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831)
	at net.minecraft.server.MinecraftServer.handler$zbl000$modifiedRunLoop(MinecraftServer.java:3390)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.plusls.carpet.network.PcaSyncProtocol.syncBlockEntityToClient(PcaSyncProtocol.java:327)
	at net.minecraft.class_3719.method_5431(class_3719.java:1024)
	at net.minecraft.class_2621.method_5434(class_2621.java:109)
	at net.minecraft.class_2614.handler$cda000$lithiumExtract(class_2614.java:4170)
	at net.minecraft.class_2614.method_11241(class_2614.java:196)
	at net.minecraft.class_2614.method_31691(class_2614.java:104)
	at net.minecraft.class_2614.method_11243(class_2614.java:120)
	at net.minecraft.class_2614.method_31692(class_2614.java:104)
	at net.minecraft.class_2818$class_5563.redirect$zbo000$checkProcessTEs(class_2818.java:1010)

-- Block entity being ticked --
Details:
	Name: minecraft:hopper // net.minecraft.class_2614
	Block: Block{minecraft:hopper}[enabled=true,facing=east]
	Block location: World: (153,130,-155), Section: (at 9,2,5 in 9,8,-10; chunk contains blocks 144,0,-160 to 159,255,-145), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Block: Block{minecraft:hopper}[enabled=true,facing=east]
	Block location: World: (153,130,-155), Section: (at 9,2,5 in 9,8,-10; chunk contains blocks 144,0,-160 to 159,255,-145), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
Stacktrace:
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:886)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:941)
	at net.minecraft.class_1937.method_18471(class_1937.java:474)
	at net.minecraft.class_3218.method_18765(class_3218.java:422)
	at net.minecraft.server.MinecraftServer.redirect$zim000$fixUpdateSuppressionCrashTick(MinecraftServer.java:4284)

-- Affected level --
Details:
	All players: 1 total; [class_3222['IRene_'/192, l='ServerLevel[world]', x=153.20, y=155.00, z=-166.30]]
	Chunk stats: 839
	Level dimension: minecraft:the_nether
	Derived: true
	Level spawn location: World: (-112,72,-256), Section: (at 0,8,0 in -7,4,-16; chunk contains blocks -112,0,-256 to -97,255,-241), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 138634588 game time, 81431 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 13877 (now: false), thunder time: 80796 (now: false)
	Known server brands: vanilla, fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:891)
	at net.minecraft.class_3176.method_3813(class_3176.java:335)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831)
	at net.minecraft.server.MinecraftServer.handler$zbl000$modifiedRunLoop(MinecraftServer.java:3390)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows Server 2012 R2 (amd64) version 6.3
	Java Version: 18.0.1.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 2833578840 bytes (2702 MiB) / 4999610368 bytes (4768 MiB) up to 7549747200 bytes (7200 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) Gold 6133 CPU @ 2.50GHz
	Identifier: Intel64 Family 6 Model 94 Stepping 3
	Microarchitecture: Skylake (Client)
	Frequency (GHz): 2.49
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: Microsoft 鍩烘湰鏄剧ず閫傞厤鍣�
	Graphics card #0 vendor: (鏍囧噯鏄剧ず鍗＄被鍨�) (0x1013)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: 0x00b8
	Graphics card #0 versionInfo: DriverVersion=6.3.9600.16384
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: RAM
	Virtual memory max (MB): 13953.55
	Virtual memory used (MB): 7568.27
	Swap memory total (MB): 5762.07
	Swap memory used (MB): 589.71
	JVM Flags: 2 total; -Xmx7200M -Xms4096M
	Fabric Mods: 
		alternate-current: Alternate Current 1.3.0
		bbor: BoundingBoxOutlineReloaded 2.4-1.17.1
		carpet: Carpet Mod 1.4.57
		carpet-extra: Carpet Extra 1.4.57
		carpet-tctc-addition: Carpet TCTC Addition 1.1.8+2285886
		carpet-tis-addition: Carpet TIS Addition 1.25.0+build.767
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		fabric: Fabric API 0.46.1+1.17
		fabric-api-base: Fabric API Base 0.4.0+cf39a74318
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.0+e821752d18
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.2+cf39a74318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.4+cf39a74318
		fabric-commands-v0: Fabric Commands (v0) 0.2.3+cf39a74318
		fabric-containers-v0: Fabric Containers (v0) 0.1.13+cf39a74318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.1+3447790d18
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.6+cf39a74318
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.15+b556f28c18
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.1+377137cc18
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.12+e99fbe1218
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.4+cf39a74318
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.8+cf39a74318
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+6617390918
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.2+cf39a74318
		fabric-language-kotlin: Fabric Language Kotlin 1.6.5+kotlin.1.5.31
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.6+0392f3a618
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.5+cf39a74318
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+cf39a74318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.7+cf39a74318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.14+cf39a74318
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.12+cf39a74318
		fabric-networking-v0: Fabric Networking (v0) 0.3.3+cf39a74318
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.1+f907116918
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.8+cf39a74318
		fabric-particles-v1: Fabric Particles (v1) 0.2.5+cf39a74318
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.8.0+ea29b33318
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+cf39a74318
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.2.1+cf39a74318
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.1+591a0f2118
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.10+f09604ce18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.9+cf39a74318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.2.0+48a9ad8918
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.3+cf39a74318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.3+3b96517518
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.4+cf39a74318
		fabricloader: Fabric Loader 0.14.7
		ferritecore: FerriteCore 3.1.0
		hologram-api: Hologram API 0.2.1+1.17.1
		ivan-carpet-addition: Ivan Carpet Addition 2.1.1
		java: Java HotSpot(TM) 64-Bit Server VM 18
		krypton: Krypton 0.1.4
		lazydfu: LazyDFU 0.1.2
		ledger: Ledger 1.1.1
		lithium: Lithium 0.7.5
		luckperms: LuckPerms 5.3.84
		minecraft: Minecraft 1.17.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.0
		org_yaml_snakeyaml: snakeyaml 1.29
		packet_tweaker: Packet Tweaker 0.2.0+1.17.1
		pca: Plusls carpet addition mod 0.2.5
		perplayerspawns: Example Mod 1.17-2.0.0
		placeholder-api: Placeholder API 1.1.2+1.17.1
		polymer: Polymer 0.1.8+1.17.1
		server_translations_api: Server Translations API 1.4.8+1.17
		sgui: sgui 1.0.0-rc5+1.17.1
		skinrestorer: Skin Restorer 1.0.4
		starlight: Starlight 1.0.0+fabric.73f6d37
		syncmatica: Syncmatica 1.16.5-0.3.2
		universal-graves: Universal Graves 1.1.4+1.17.1
		viabackwards: ViaBackwards 4.0.1
		viafabric: ViaFabric 0.4.3+203-main
		viafabric-mc117: ViaFabric for 1.17 0.4.3+203-main
		viarewind: ViaRewind 2.0.1
		viaversion: ViaVersion 4.0.1
		voicechat: Simple Voice Chat 1.17.1-2.2.38
		xlpackets: XLPackets 2.1-1.17.1
	Player Count: 1 / 50; [class_3222['IRene_'/192, l='ServerLevel[world]', x=153.20, y=155.00, z=-166.30]]
	Data Packs: vanilla, file/XKsmallmap1.17-1.zip (incompatible), file/craft_head_datapack.zip (incompatible), Fabric Mods
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by wendavid552** [comment]
使用上讲，建议升级到carpet-tis-addition v1.27.0以上版本，此版本之下并没有加入largeBarrel，在[错误处](https://github.com/plusls/plusls-carpet-addition/blob/e2d5c43a3f9d668d36f76a5f8d8110097574ee7f/src/main/java/com/plusls/carpet/network/PcaSyncProtocol.java#L327)没有判断该规则是否存在。
